feat: upgrade sls to 3.26.0
helsingborg-stad/helsingborg-io-sls-resources pull request #125
Opened 2023-01-25 15:04 UTC by dannil76

Uppgraderat Serverless till 3.26

Kör git checkout på denna branch
Se till att du har Serverless 3.26 globalt installerat på datorn

Deploya och se att det lirar.

2023-01-26 07:31 UTC, helsingborgsstad commented
Task linked: [CU-3x150gp Uppdatera Serverless till version 3.x](https://app.clickup.com/t/3x150gp)

2023-01-27 09:16 UTC, MasterKenth commented on services/gateway/root/serverless.yml
> +  # logs:
Kommenterad kod? Bort ✋🛑

2023-01-27 09:33 UTC, MasterKenth requested changes

2023-01-27 09:33 UTC, MasterKenth commented on services/gateway/root/serverless.yml
> +  # logs:
Kommenterad kod? Bort ✋🛑!

2023-01-27 10:34 UTC, MasterKenth approved these changes

2023-01-27 10:36 UTC, merged