Add web application firewall with ip block and some free subscriptions of bad guy blockers
helsingborg-stad/helsingborg-io-sls-resources pull request #61
Opened 2021-08-11 13:20 UTC by yo-l1982

## Feature description
This will add AWS WAF firewall and connect it to our API Gateway.
Added to this update is:

- Example IP block.
- Two subscriptions to AWS rulesets that are made to filter out bad inputs and bad reputation ip numbers(i.e ips that are known sources of attacks.)
- A commented rule(For now to keep costs down) with Bot Control for blocking bots.  https://aws.amazon.com/waf/features/bot-control/

## Solution description
Fully AWS Managed service in Cloudformation format

## What areas is affected by these changes?.
None.

## Is there any excisting behavior change of other features due to this code change?
No this hooks right in with no downtime on deploy.

## Are your code strutured in a way so that reviewers can understand it?
Everybody understands CFN right?

## Was this feature tested in the following environments?
- [x] Your personal AWS environment.
- [] Your local serverless enviorment.

2021-08-12 23:06 UTC, helsingborgsstad commented
Task linked: [CU-mqaygc Implementera Web Application Firewall (AWS WAF)](https://app.clickup.com/t/mqaygc)

2021-08-20 07:14 UTC, dannil76 requested changes
Got following error when deploying service gateway root
`
Stack Outputs
ApiGatewayRestApiId: 0kwx0cd26m
ApiRootLambdaFunctionQualifiedArn: arn:aws:lambda:eu-north-1:020402302769:function:gateway-root-dev-apiRoot:3
ServiceEndpoint: https://0kwx0cd26m.execute-api.eu-north-1.amazonaws.com/dev
ApiGatewayRestApiRootResourceId: ubfqauvhoa
ServerlessDeploymentBucketName: gateway-root-dev-serverlessdeploymentbucket-1ebasnkfyn0wt


 Serverless Error ----------------------------------------

  Rest API id could not be resolved.
  This might be caused by a custom API Gateway configuration.

  In given setup stage specific options such as `tracing`, `logs` and `tags` are not supported.

  Please update your configuration (or open up an issue if you feel that there's a way to support your setup).

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.1
     Framework Version:         2.49.0
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.1


 Error ---------------------------------------------------

  Error: Cannot find module '@serverless/dashboard-plugin/package'
  Require stack:
  - /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js
  - /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/cli/handle-error.js
  - /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/scripts/serverless.js
  - /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/bin/serverless.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
      at Function.Module._load (internal/modules/cjs/loader.js:725:27)
      at Module.require (internal/modules/cjs/loader.js:952:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js:184:41
      at module.exports (/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js:210:5)
      at runNextTicks (internal/process/task_queues.js:58:5)
      at processImmediate (internal/timers.js:434:9)
      at async module.exports (/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/cli/handle-error.js:176:32)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.1
     Framework Version:         2.49.0
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.1

/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/node_modules/essentials/index.js:12
		throw reason;
		^

Error: Cannot find module '@serverless/dashboard-plugin/package'
Require stack:
- /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js
- /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/cli/handle-error.js
- /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/scripts/serverless.js
- /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js:184:41
    at module.exports (/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js:210:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/cli/handle-error.js:176:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/utils/telemetry/generatePayload.js',
    '/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/lib/cli/handle-error.js',
    '/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/scripts/serverless.js',
    '/Users/dannilsson/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/bin/serverless.js'
  ]
}`

2021-08-20 07:26 UTC, dannil76 commented
Tried a second time and this time removed
`  tracing:
    apiGateway: true
    lambda: true`

and removed plugin serverless-plugin due this is not relevant in this case

Deployment worked this time with no errors.
Confirm that the section 'Web ACL' is indeed set

Think this is okey then?

2021-08-20 07:26 UTC, dannil76 approved these changes

2021-09-22 13:58 UTC, merged