feat: upgrade features project
helsingborg-stad/helsingborg-io-sls-resources pull request #82
Opened 2021-12-07 15:45 UTC by petter-a

# Upgrade Resources project
1. Change node version from 10 to 16
2. Upgrade packages in package.json
3. Add retention for API gateway logs for 2 weeks
4. Add AccessLogs for API gateway
5. Fixed legacy configuration for eslint

2021-12-13 09:50 UTC, yo-l1982 approved these changes
Works fine here.

2021-12-21 08:24 UTC, karlknowit requested changes

2021-12-21 08:24 UTC, karlknowit commented on services/gateway/root/serverless.yml
> +      executionLogging: true
true is the default value for executionLogging

2021-12-21 08:24 UTC, karlknowit commented on services/gateway/root/serverless.yml
> +      accessLogging: true
true is the default value for accessLoggin

2021-12-21 12:00 UTC, yo-l1982 commented on services/gateway/root/serverless.yml
> +      executionLogging: true
It doesnt seem to be activated on the AWS dev environment and it should be if these are defaulted to true imo (as they were missing before).
Maybe we should keep them in this pr?

2021-12-21 12:23 UTC, petter-a commented on services/gateway/root/serverless.yml
> +      accessLogging: true
@karlknowit so they say.... but its not in practise

2021-12-21 12:29 UTC, petter-a commented on services/gateway/root/serverless.yml
> +      executionLogging: true
My experience with these settings are that they doesn't always "bite". It is a bit random. I agree that the documentation states that both execution logging and access logging are enabled by default but it did not appear before I actually enforced it. I will do another check of the Cloudformation template generated....

2021-12-21 12:51 UTC, karlknowit commented on services/gateway/root/serverless.yml
> +      executionLogging: true
We could keep them for clarification and to be sure that they values are actually set. I don't mind that

2021-12-21 12:55 UTC, karlknowit approved these changes

2021-12-21 13:41 UTC, petter-a commented on services/gateway/root/serverless.yml
> +      accessLogging: true
The logic in serverless seems to indicate that it indeed does enable access logging by default. However, it doesn't seem to work all the time. I will remove the override though...

const accessLogging = logs.accessLogging == null ? true : logs.accessLogging;

2021-12-21 13:57 UTC, petter-a commented on services/gateway/root/serverless.yml
> +      executionLogging: true
Decided to keep them for now. If nothing else, it doesn't harm

2021-12-21 13:58 UTC, petter-a commented on services/gateway/root/serverless.yml
> +      accessLogging: true
Decided to keep it for now as it doesn't cause any harm

2021-12-21 13:59 UTC, merged